apiVersion: v1
kind: Service
metadata:
  name: contato-worker-api
spec:
  selector:
    app: contato-worker-api 
  ports:
    - protocol: TCP
      port: 8080         # A porta onde o serviço será exposto
      targetPort: 8080   # A porta dentro do container
  type: ClusterIP  
